name: Hassfest Validation

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
